# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ub6dtTPB-byXXVbilHXPzQhoAAG7Ccp
"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

df = pd.read_csv("https://raw.githubusercontent.com/sahil-gidwani/DL/main/data/letter-recognition.csv")
df.head()

df.isnull().sum()

df.info()

x=df.iloc[:,1:].values
y=df.iloc[:,0].values

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

model=SVC()
model

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

score=accuracy_score(y_test,y_pred)
print(score)

